controller_list:
  - name: fake_UR5_movegroup_controller
    type: $(arg fake_execution_type)
    joints:
      - ur5/shoulder_pan_joint
      - ur5/shoulder_lift_joint
      - ur5/elbow_joint
      - ur5/wrist_1_joint
      - ur5/wrist_2_joint
      - ur5/wrist_3_joint
  - name: fake_Robotiq_movegroup_controller
    type: $(arg fake_execution_type)
    joints:
      - finger_joint
initial:  # Define initial robot poses per group
  - group: UR5_movegroup
    pose: UR_INIT
  - group: Robotiq_movegroup
    pose: RBT_OPEN