UR5_movegroup_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ur5/shoulder_pan_joint
    - ur5/shoulder_lift_joint
    - ur5/elbow_joint
    - ur5/wrist_1_joint
    - ur5/wrist_2_joint
    - ur5/wrist_3_joint
  gains:
    ur5/shoulder_pan_joint:
      p: 4000
      d: 200
      i: 1
      i_clamp: 1
    ur5/shoulder_lift_joint:
      p: 10000
      d: 200
      i: 1
      i_clamp: 1
    ur5/elbow_joint:
      p: 2000
      d: 20
      i: 1
      i_clamp: 1
    ur5/wrist_1_joint:
      p: 500
      d: 1
      i: 1
      i_clamp: 1
    ur5/wrist_2_joint:
      p: 500
      d: 1
      i: 1
      i_clamp: 1
    ur5/wrist_3_joint:
      p: 10
      d: 0.1
      i: 0
      i_clamp: 1
  constraints:
      stopped_velocity_tolerance: 0.0
Robotiq_movegroup_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - finger_joint
  gains:
    finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
  constraints:
      stopped_velocity_tolerance: 0.0