controller_list:
  - name: UR5_movegroup_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - ur5/shoulder_pan_joint
      - ur5/shoulder_lift_joint
      - ur5/elbow_joint
      - ur5/wrist_1_joint
      - ur5/wrist_2_joint
      - ur5/wrist_3_joint
  - name: Robotiq_movegroup_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - finger_joint